# Generated by Django 5.0.7 on 2024-07-26 19:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_alter_standard_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
